server:
  port: 8080

spring:
  application:
    name: webgitstats
  datasource:
    platform: h2
    url: jdbc:h2:file:~/.webgitstats/db.data
    driverClassName: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/init_schema.sql
    data: classpath:db/init_data.sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
      path: /h2
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
